[project]
name = "bfiola-operator-core"
version = "0.0.0"
dependencies = [
    "fastapi",
    "kopf",
    "kubernetes",
    "pydantic",
    "uvicorn"
]

[project.optional-dependencies]
dev = [
    "bfiola-devtools"
]
